services:
  - type: web
    name: flashcard-app
    env: python
    plan: professional
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DB_TYPE
        value: postgresql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: FLASK_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true

databases:
  - name: flashcard-db
    databaseName: flashcard_app
    user: flashcard_user
    plan: professional 