services:
  - type: web
    name: flashcard-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DB_TYPE
        value: sqlite
      - key: DB_PATH
        value: /opt/render/project/src/flashcards.db
      - key: FLASK_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true 