services:
  - type: web
    name: flashcard-app
    env: python
    plan: professional
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DB_TYPE
        value: postgresql
      - key: DB_HOST
        value: dpg-d263vjuuk2gs73bfe640-a.singapore-postgres.render.com
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        value: anki_db
      - key: DB_USER
        value: anki_user
      - key: DB_PASSWORD
        value: 0sUr3K1NauZBEW5tsu7NTKRFibzM7GoB
      - key: FLASK_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true

databases:
  - name: flashcard-db
    databaseName: anki_db
    user: anki_user
    plan: professional 